# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/web"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  log = "air.log"

[log]
  time = true
